### ISSUE TITLE
Support configuration scopes

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#1725]
Quoting from @akesandgren:

> It would be somewhat more user friendly if it augmented the settings.py from the user with the core/settings.py. Although I would prefer if it did read and augment config files in the order -C, $HOME/..., the other ones from "Locating the Configuration File", core/settings.py.
> Or perhaps one should do it the other way around and override with whatever values comes from the read file, i.e. read core/settings.py, XDG_DATA/reframe.d/settings.py, $HOME/... (also using the XDG_USER style), and finally any -C config files.

I'm not entirely sure about chaining the `-C` option, but I'm totally in favor of supporting configuration scopes, so that you only redefine the relevant parts of the documentation.

**Comment by akesandgren** [comment]
I was thinking of a -C file1:file2:file3 which would be the same as reading from the other files above.
