### ISSUE TITLE
Passing `--performance-report` to generated GitLab CI pipeline

### ISSUE THREAD

**Issue by flx42** [reframe-hpc/reframe#2467]
Hello,

It would be great to be able to inject additional arguments such as `--performance-report` and `--strict` when creating a GitLab CI file with `--ci-generate`. Right now, using those arguments seems to have no effect when `--ci-generate` is used.

Alternatively, I suppose a more generic approach could be to have `--ci-generate` simply passthrough the `--mode` argument, and thus my problem could be fixed with something like this:
```console
$ cat settings.py
[...]
    'modes': [
        {
           'name': 'ci',
           'options': [
               '--performance-report',
               '--strict',
           ]
        },
    ]

$ reframe -R -c ./tests --ci-generate=./pipeline.yml --mode=ci 
```

**Comment by vkarak** [comment]
Hi @flx42, thanks for your suggestion. I think it makes sense. In the past we have had a couple of PRs to pass through specific options to the child pipelines (see #2137 and #2205). I think that we should generalise this mechanism and pass any options that could potentially make sense to the child pipeline.

**Comment by flx42** [comment]
Thanks a lot for adding this, I verified it works fine!
