### ISSUE TITLE
Prepending system information to `handlers_perflog` output

### ISSUE THREAD

**Issue by flx42** [reframe-hpc/reframe#2501]
On a development cluster, we only have a few partitions but the system configuration changes frequently on those nodes:
- The version of the Linux kernel changes frequently
- The NVIDIA driver version changes frequently
- Various other drivers/firmware can also be modified

We use a simple `handlers_perflog` of type `file` to save the performance report of a Reframe run during a daily run. To make it easier to compare runs, it would be great to be able to store system information at the beginning of this output file before the performance report, e.g. something like this:
```
# Linux 5.17.0, NVIDIA Driver 510.47.03, MOFED 5.6-1.0.3.3
Stream|Copy=337991.6|ref=340000 (l=-0.03, u=0.03)|MB/s
[...]
```

Is this possible today? I couldn't find a way.
If not, consider this issue a RFE to add support for this. Thank you!

**Comment by rsarm** [comment]
One solution could be to create a loggable variable and pass to it in a hook the information you need to have in the performance log. For instance
```python
@rfm.simple_test
class test(rfm.RegressionTest):
    system_info = variable(dict, loggable=True)
    ...

@run_after('setup')
def set_system_info(self):
    self.system_info = get_system_info()
```
One idea for that is to have a base class defining that hook from which your test could inherit.

The variable can be passed in the `format` of the handler perflog in the configuration. Something like
```python
'handlers_perflog': [
    {
        'type': 'filelog',
        'prefix': '...',
        'level': 'info',
        'format': '%(check_system_info)s  ...'
        'datefmt': '%FT%T%:z',
        'append': True
    }
```
That will print the information in every entry of the perflog though.

Would that be a solution for you?

**Comment by flx42** [comment]
This is a neat trick, but this would have to be done for all tests, right? (or through a base test class that all tests inherits)

Thanks!

**Comment by flx42** [comment]
Yes, but we also just decided to significantly increase the amount of system info we are going to log, we are going to add the full output of this command (among other things):
```
nvidia-smi --query-gpu=index,pci.bus_id,serial,inforom.img,vbios_version,driver_version,power.limit,enforced.power.limit,power.draw,temperature.gpu,temperature.memory,pcie.link.gen.current,memory.total,memory.reserved,memory.used,memory.free,ecc.errors.corrected.volatile.total,ecc.errors.corrected.aggregate.total,ecc.errors.uncorrected.volatile.total,ecc.errors.uncorrected.aggregate.total --format=csv
```
So that's not something we would want on each line. Instead we will take a different strategy for logging the system info + the performance results.
Thanks a lot for the tip above, I will actually use that for another setting I want to log.

Feel free to close this issue unless that's something you still want to work on for a different reason.
