### ISSUE TITLE
Small Documentation Issue

### ISSUE THREAD

**Issue by Lewih** [reframe-hpc/reframe#2561]
https://github.com/reframe-hpc/reframe/blob/431ca172b2074c8f570e27f89e8f377b8572c424/reframe/core/logging.py#L343

It is looking for `url` entry in config file, but in the documentation [https://reframe-hpc.readthedocs.io/en/latest/config_reference.html#the-httpjson-log-handler](https://reframe-hpc.readthedocs.io/en/latest/config_reference.html#the-httpjson-log-handler) the example shows `address`.

**Comment by vkarak** [comment]
Thanks @Lewih for spotting this!
