### ISSUE TITLE
Test library shmem sanity function finds multiple 'Bandwidth' statements

### ISSUE THREAD

**Issue by nordmoen** [reframe-hpc/reframe#2600]
I was setting up the `hpctestlib.microbenchmarks.gpu.shmem` test on our local cluster and encountered what I believe to be a bug in the sanity checking.

The problem appeared when trying to sanity check the number of GPUs. On our cluster we output additional information in the Slurm output, some of which contained the words `Bandwidth`. This fit the regex in `assert_count_gpus` which resulted in an inflated GPU count.

To fix this I changed the regex from `r'Bandwidth'` to `r'Bandwidth\((int|double)\)'` to better fit what I perceived in the test output to be the correct result sentence.

**Comment by vkarak** [comment]
Thanks for reporting this @nordmoen! We can fix the regex.
