### ISSUE TITLE
Stream tests in the tutorials fail

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2614]
The source cannot be fetched. I think that we should simply add the source code in the repo, if possible.

**Comment by teojgo** [comment]
Including it is straightforward, since we already have it here: https://github.com/reframe-hpc/reframe/blob/master/tutorials/cscs-webinar-2022/tests/src/stream.c

**Comment by teojgo** [comment]
@vkarak which tutorial does not work? For me they work fine.

**Comment by vkarak** [comment]
It was failing for me when I opened the issue, but yesterday seemd to be fine again. We could close it.
