### ISSUE TITLE
Consider removing the `--strict` option

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2626]
Since now we support setting variables from the command line, this is equivalent to `-S strict_check=1`. Actually, it's almost equivalent, because the `-S` variant will not have an effect is somebody sets this variable in a hook, but I don't think that's a common case and we gain in conformity with the rest of the variables.

**Comment by ekouts** [comment]
I am not really against it, but there are cases where a user may want to set strict certain cases of the test in a post-init decorator. One could be the that they want to run the test in `strict` mode in production systems and just log the performance in tds systems. For the case of different system they could have different invocations with/without the option, but the distinction of "production"/"tds" testcase can come in theory from a variable/parameter of the version of the software or anything.

**Comment by vkarak** [comment]
I don't have a strong opinion either on that, except that this option is an artefact of limitations that we had in the past. But we can leave it as the semantics are slightly different. Another similar option that we could remove though is the `--force-local`, since it does actually set the `local` attribute in the test. I'm going to open an issue for that and discuss there.

**Comment by vkarak** [comment]
This is very much related to #2629 in principle.
