### ISSUE TITLE
graylog initialization error handling

### ISSUE THREAD

**Issue by dslarm** [reframe-hpc/reframe#2654]
When using the graylog framework, if the pygelf module is not installed, the error is "could not initialize the graylog handler; ignoring".  No other error is flagged.

I spent a while 'fixing' graylog server firewalls - assuming the error was elsewhere before looking at the source of core/logging.py

It would be helpful to report the error that module cannot be imported - specifically, in _create_graylog_handler - the ImportError exception handler should log before it returns None.

**Comment by vkarak** [comment]
Hi @dslarm, thanks for the suggestion! It definitely make sense to have a more precise message there.
