### ISSUE TITLE
Remove the `schedulers` section from the configuration

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2669]
And move it under the `partitions`. These are options tied to the scheduler of each partition.

**Comment by ireed** [comment]
Is there a way to change or set the scheduler inside a test? For example, i can do 

> @run_before('run')
>  def prepare_run(self):
>      self.job.launcher = getlauncher('srun')()

 to set the launcher, or change the change it from whatever is in the config file. But using something like 

> @run_before('run')
> def prepare_run(self):
>    self.job.scheduler= getscheduler('slurm')()

will either be ignored or give a runtime error such as -- _Reason: attribute error: can't set attribute_ -- if i already have a config file.

I see no code, tests, or examples in the repo that demonstrates changing the scheduler from what is in the config file.

**Comment by vkarak** [comment]
Hi @ireed, no you can't change the scheduler cos there is one instance per partition, as the scheduler needs to know of all the jobs on the partition in order to optimise its queries, e.g., check the status of all jobs at once. You could potentially hack it in, but wouldn't defining a new partition help?
