### ISSUE TITLE
Variables are not set with the deprecated `variables` attribute

### ISSUE THREAD

**Issue by ekouts** [reframe-hpc/reframe#2681]
The `variables` attribute gives a deprecation warning but doesn't work anymore. The `export ...` command is not emitted in the script. Could be because of #2649 or #2648 maybe?

It works perfectly fine, when the test sets `env_vars`.

Test to reproduce:
```python
import reframe as rfm
import reframe.utility.sanity as sn

@rfm.simple_test
class CheckVars(rfm.RunOnlyRegressionTest):
    valid_systems = ['*']
    valid_prog_environs = ['*']
    # env_vars = {'VAR': 'FOO'}
    variables = {'VAR': 'FOO'}
    executable = 'echo'
    executable_opts = ['$VAR']

    @sanity_function
    def check_exit(self):
        return sn.assert_found('FOO', self.stdout)
```

**Comment by vkarak** [comment]
It's indeed a bug; we don't treat the case where an aliased variable is set in the class body. It seems that the assignment is not delegated correctly to the target variable.
