### ISSUE TITLE
Skip bootstrap step at topology detect

### ISSUE THREAD

**Issue by adrien-cotte** [reframe-hpc/reframe#2690]
Unfortunately, `RFM_REMOTE_DETECT=TRUE` calls `pip` via `bootstrap.sh`.
I am not able to use `pip` on my computer (usual proxy stuff).

@vkarak suggests to add an option to avoid the bootstrap and simply copy the dependencies over to the remote host.

I'll be glad to contribute but I don't know what to do exactly.

**Comment by akesandgren** [comment]
I'd vote for adding a "reframe_module" definition (general and/or part partition) which, if defined, should be used instead of the bootstrap stuff for doing remote_detect

**Comment by vkarak** [comment]
Yep, that's the issue #2292, right?

**Comment by akesandgren** [comment]
Ah yes, that's the one I opened before. Had forgotten about it.
