### ISSUE TITLE
Missing line break in reframe.core.systems.SystemPartition in the docco

### ISSUE THREAD

**Issue by akesandgren** [reframe-hpc/reframe#2748]
There is a missing line break between
"property name" and "property prepare_cmds"
under reframe.core.systems.SystemPartition in the documentation

**Comment by vkarak** [comment]
Oh yes, I've seen that I have no idea how to fix the formatting in Sphinx :-) I believe it's the adaptive layout. The docs are rendered correctly in a narrower browser window or if you add to them more text. I will mark it as "won't fix" unless you have a solution :-D
