### ISSUE TITLE
Introduce more advanced testing for the `httpjson` handler

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2760]
Currently, we only check that it is initialised correctly, but we don't check its functionality in the unit tests. To achieve that, we would need to spin up a dummy http server that would consume and validate the json that the handler sends.

**Comment by ekouts** [comment]
Maybe this is useful: https://httpretty.readthedocs.io/en/latest/

**Comment by vkarak** [comment]
I found also the [pytest-httpserver](https://pytest-httpserver.readthedocs.io/en/latest/index.html) which as integration with pytest. I'm not sure if httpretty has.

**Comment by vkarak** [comment]
I think that I will close this, as it's not as straightforward as I initially thought. Those libraries are good in testing direct requests. In our case, the request happens behind the log handler an in order to get a proper request you need to run a test. Therefore you can only test in the `test_policies.py` where we run the full pipeline. Also, we would not be able to test the response of the server, as this is is not processed at all in the httpjson handler, so the server would have to do some sort of validation. But then the question is how to notify the case of failure? I think it's too much fuss and the `debug` option of the `httpjson` handler can be really helpful in debugging the problematic requests.
