### ISSUE TITLE
Test listing should also list the fixture variable names since this is required by the `-S` option

### ISSUE THREAD

**Issue by ekouts** [reframe-hpc/reframe#2763]
This is about the wrongly documented behavior of `-S` from #2757.

**Comment by vkarak** [comment]
It might also be a bug in the code and the documentation could just be correct. ;-) I'll have to look at it.

**Comment by vkarak** [comment]
So, the documentation _is_ correct, but not so accurate. The `FIXT` refers to the _fixture variable name_, not the _fixture class name_. Add the following in the `fetch_osu_benchmarks`:

```python
    @run_after('init')
    def foo(self):
        print(self.descr)
```

and then try this:

```
./bin/reframe -C tutorials/config/daint.py -c tutorials/fixtures/osu_benchmarks.py --skip-system-check --skip-prgenv-check -l -n osu_latency_test -S osu_latency_test.osu_binaries.osu_benchmarks.descr=hello -L
```

This will correctly print "hello." What is not clear from the docs is that `FIXT` refers to the class name and and there is no way to know the variable name from the test listing, which is confusing. I will expand the docs and update the test listing (perhaps in its detailed form, so as to print the fixture variable name).
