### ISSUE TITLE
Do not change the order of execution of a base class hook when overriding it

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2800]
Consider the following test:

```python
import reframe as rfm
import reframe.utility.sanity as sn


@rfm.simple_test
class TestA(rfm.RunOnlyRegressionTest):
    valid_systems = ['*']
    valid_prog_environs = ['*']
    x = variable(int)

    @run_before('run')
    def setx(self):
        self.x = 10

    @run_before('run')
    def setup_executable(self):
        self.executable = f'echo {self.x}'

    @sanity_function
    def validate_test(self):
        return sn.assert_found(f'{self.x}', self.stdout)


@rfm.simple_test
class TestB(TestA):
    @run_before('run')
    def setx(self):
        self.x = 20
```

`TestA` runs fine but `TestB` fails with the following error:

```
  * Reason: attribute error: ../misc/rfm-support/slack/fontenaille_hooks/simple.py:19: required variable 'x' has not been set
        self.executable = f'echo {self.x}'
```

The order of execution for `TestA` is the expected one:

```
reframe -c /path/to/test.py -n ^TestA --describe | jq .[].pipeline_hooks
```

```json
{
  "pre_run": [
    "setx",
    "setup_executable"
  ]
}
```

For `TestB` however, the order is inverted:

```json
{
  "pre_run": [
    "setup_executable",
    "setx"
  ]
}
```

Therefore, when `setup_executable()` runs, `x` is undefined. The problem is that pipeline hooks follow the reverse MRO order when they are executed, but this applies also when a hook is overriden. As a result, `TestB.setx` is now part of the derived class and will therefore execute after every hook of the base class.

The desired behaviour would be to replace the base hook but not to move its position in the execution order.

**Comment by Clement-Fontenaille** [comment]
Hi,

To override hooked methods without impacting execution order, you may not decorate the overriding definition.
However, when doing this, the hooked method is not executed when executing the test that defines the override.
However², followup derived classes do inherid the overriding method and the hook that executes it.

So I came up with this decorator that replace the decorated class with an empty inheriting class 'on the fly'.
Since the class created in the decorator does not itself declare any override, the hook is correctly executed, and the overriding method is called in adequate order.

```python3
import sys
import reframe as rfm
import reframe.utility.sanity as sn
from reframe.core.meta import make_test

def enable_hook_override(cls):
    cls_w = make_test(cls.__name__, (cls, ), {})
    # use setattr to make it as if cls_w was declared in cls's module
    setattr(sys.modules[cls.__module__], cls_w.__name__, cls_w)
    setattr(cls_w, '__module__', cls.__module__)
    return cls_w

@rfm.simple_test
class TestA(rfm.RunOnlyRegressionTest):
    valid_systems = ['*']
    valid_prog_environs = ['*']
    x = variable(int)
    
    @run_before('run')
    def setx(self):
        self.x = 10
    
    @run_before('run')
    def setup_executable(self):
        self.executable = f'echo {self.x}'

    @sanity_function
    def validate_test(self):
        return sn.assert_found(f'{self.x}', self.stdout)


@rfm.simple_test
@enable_hook_override
class TestB(TestA):
    
    # does not redefine the hook
    def setx(self):
        self.x = 20
```
