### ISSUE TITLE
Store the log files in the run report

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2811]
Similarly, we should also store the full list of config files, instead of a single one.

**Comment by vkarak** [comment]
@ekouts, yes but the generated report currently stores only one of the configuration files.

**Comment by ekouts** [comment]
Could you give me an example, for me it shows all the config files that are passed through the cli, with `-C`?

**Comment by vkarak** [comment]
@ekouts, Indeed they are there. Perhaps I was looking at an older version.
