### ISSUE TITLE
Add cli option to inject environment variables for a test

### ISSUE THREAD

**Issue by teojgo** [reframe-hpc/reframe#2824]
This could work similarly to the `-S` option where we inject test specific variables but for environment variables

**Comment by vkarak** [comment]
Wouldn't the `-S env_vars=VAR:VAL,..` work?

**Comment by teojgo** [comment]
> Wouldn't the `-S env_vars=VAR:VAL,..` work?

True, I forgot that I can indeed set dictionaries as well.
