### ISSUE TITLE
Reframe on Isambard bootstrapping error related with urllib package version

### ISSUE THREAD

**Issue by kaanolgu** [reframe-hpc/reframe#2860]
I have installed the ReFrame with Spack and trying to run it initially but it gives me the following error message :
```
[br-kolgu@login-01 reframe-4.0.4-aywne5pbfdemxvulmokilxvtpjzu6oo4]$ ./bootstrap.sh
==> python3 -m ensurepip --root /home/br-kolgu/excalibur-tests/spack/isambard-cascadelake/compute-node/opt/cray-rhel8-broadwell/gcc-9.2.0/reframe-4.0.4-aywne5pbfdemxvulmokilxvtpjzu6oo4/external/ --default-pip
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages
Requirement already satisfied: pip in /usr/lib/python3.6/site-packages
==> python3 -m pip install --no-cache-dir -q --upgrade pip --target=external/
==> python3 -m pip install --no-cache-dir -q -r requirements.txt --target=external/ --upgrade
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
botocore 1.18.15 requires urllib3<1.26,>=1.20, but you have urllib3 1.26.15 which is incompatible.
````

**Comment by teojgo** [comment]
@kaanolgu can you try the bootstrapping with `--pip-opts '--ignore-installed'` ?

**Comment by teojgo** [comment]
@kaanolgu can you try with `/bootstrap.sh --pip-opts '--no-deps'` ?

**Comment by teojgo** [comment]
@kaanolgu that's different. I suggest to close this and you can join the Slack channel so that it's easier to debug it.

**Comment by kaanolgu** [comment]
@teojgo  I was planning to ask there but the link is broken for slack channel 

Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

**Comment by teojgo** [comment]
> @teojgo I was planning to ask there but the link is broken for slack channel
> 
> Application error An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command

Ok, I will check with the other ReFrame developers and come back to you.

**Comment by vkarak** [comment]
Yes, we just recently realised that the Slack link was broken! This is fixed in #2862. Please use the link in that PR to join!

**Comment by vkarak** [comment]
As for the error here. When you  install reframe through spack, you should not run the `./bootstrap.sh` script. All the dependencies are installed through Spack, so the `reframe` command should just work.

**Comment by teojgo** [comment]
@kaanolgu the slack problem was fixed. You can join now.

**Comment by kaanolgu** [comment]
Thank you joined, closing this to ask questions in slack!
