### ISSUE TITLE
Formatting is broken in `extractall_s()` docs

### ISSUE THREAD

**Issue by vkarak** [reframe-hpc/reframe#2909]
https://reframe-hpc.readthedocs.io/en/stable/deferrable_functions_reference.html#reframe.utility.sanity.extractall_s

**Comment by vkarak** [comment]
Since the default branch is `develop`, only merges to this branch close automatically issues. For the issues that are solved by PRs to `master`, we move them manually to the "Merge to develop" stage and will close them as soon as `master` is merged into `develop`, i.e., just after a patch-level release.

**Comment by jack-morrison** [comment]
Makes sense now - thanks!
