### ISSUE TITLE
CPU autodetection fails on graviton nodes in AWS

### ISSUE THREAD

**Issue by casparvl** [reframe-hpc/reframe#2950]
We have a test infrastructure based on Cluster in the Cloud in AWS. Here, we have access to some Graviton 2 and Graviton 3 nodes. I found that CPU autodetection jobs would never finish on these nodes. Creating an interactive allocation, I found that 

```
python3 -m pip install --no-cache-dir --upgrade pip -q --target=external/
```

from the `bootstrap.sh` that hangs. Rerunning this with more verbose output `-vvv` instead of `-q`), I see that it hangs at:
```
Installing collected packages: pip

  Creating /tmp/tmprlinfxyx/bin
  changing mode of /tmp/tmprlinfxyx/bin/pip to 755
  changing mode of /tmp/tmprlinfxyx/bin/pip3 to 755
  changing mode of /tmp/tmprlinfxyx/bin/pip3.6 to 755
Successfully installed pip-21.3.1
Cleaning up...
Starting new HTTPS connection (1): pypi.python.org
https://pypi.python.org:443 "GET /pypi/pip/json HTTP/1.1" 301 122
Starting new HTTPS connection (1): pypi.org
https://pypi.org:443 "GET /pypi/pip/json HTTP/1.1" 200 37694
```
So, it seems to complete, then try to make a new connection, then hangs. 

It _might_ not be a ReFrame-specific issue, but I figured I'd ask anyone: has anyone ever seen this before, and/or used CPU autodetect succesfully on `aarch64` architectures?

**Comment by vkarak** [comment]
Haven't seen this before... I guess you're trying with `RFM_REMOTE_DETECT=y` and it hangs during `./bootstrap.sh` in the auto-detection script? Does it produce eventually the processor info file? Have you tried logging in directly on the target node and executing `reframe --detect-host-topology`?

**Comment by casparvl** [comment]
>  I guess you're trying with RFM_REMOTE_DETECT=y and it hangs during ./bootstrap.sh in the auto-detection script?

Yes, exactly.

> Does it produce eventually the processor info file?

No it doesn't

> Have you tried logging in directly on the target node and executing reframe --detect-host-topology?

Yep, that works fine. The issue is really the bootstrap, it simply does't get to the point where it would run `reframe --detect-host-topology`

**Comment by vkarak** [comment]
We've just released 4.3.2 that executes the bootstrap steps in a virtual environment. Could you try that out and check if the error persists?

**Comment by casparvl** [comment]
```
reframe -C ~/test-suite/config/${RFM_CONFIG_NAME} -c ${TEMPDIR}/test-suite/eessi/testsuite/tests/apps/ -R -t CI ${TAGS} -l
Detecting topology of remote partition 'citc:aarch64-graviton2-8c-16gb': this may take some time...
WARNING: failed to retrieve remote processor info: [Errno 2] No such file or directory: 'topo.json'
```

I've noticed it quite tricky to debug errors in the rfm_autodetect job. It'd be nice if one could easily check the stdout and stderr for the job, as well as reproduce it interactively. But, I don't think the staging dir for this job is preserved, is it? The only way I found was to copy the temporary dir it creates while running the job, and then run that interactively. (interactively, the bootstrap script now completed succesfully, so I'm not sure what goes wrong here in the job. It might be some very silly mistake...)

**Comment by vkarak** [comment]
If you run with increased verbosity, you should be able to see also the submitted script and the stdout/stderr. For reproducing it interactively, maybe some more information would be needed but I'm not sure (need to try it).

**Comment by casparvl** [comment]
Right, should have thought of that. Indeed, this prints the *.out and *.err files. Here's the output: 

```
Detecting topology of remote partition 'citc:aarch64-graviton2-8c-16gb': this may take some time...
submitting detection script
--- /mnt/shared/home/casparvl/rfm.5_dw_ie2/rfm-detect-job.sh ---
#!/bin/bash
#SBATCH --job-name="rfm-detect-job"
#SBATCH --ntasks=1
#SBATCH --output=rfm-detect-job.out
#SBATCH --error=rfm-detect-job.err
#SBATCH --export=NONE
#SBATCH --constraint=shape=c6g.2xlarge

_onerror()
{
    exitcode=$?
    echo "-reframe: command \`$BASH_COMMAND' failed (exit code: $exitcode)"
    exit $exitcode
}

trap _onerror ERR

./bootstrap.sh
srun ./bin/reframe --detect-host-topology=topo.json

--- /mnt/shared/home/casparvl/rfm.5_dw_ie2/rfm-detect-job.sh ---
job finished
--- /mnt/shared/home/casparvl/rfm.5_dw_ie2/rfm-detect-job.out ---
==> python3 -m venv /tmp/tmp.3qVpCPJHyR
-reframe: command `./bootstrap.sh' failed (exit code: 1)

--- /mnt/shared/home/casparvl/rfm.5_dw_ie2/rfm-detect-job.out ---
--- /mnt/shared/home/casparvl/rfm.5_dw_ie2/rfm-detect-job.err ---
Unable to symlink '' to '/tmp/tmp.3qVpCPJHyR/bin/rfm.5_dw_ie2'
Error: [Errno 2] No such file or directory: ''

--- /mnt/shared/home/casparvl/rfm.5_dw_ie2/rfm-detect-job.err ---
WARNING: failed to retrieve remote processor info: [Errno 2] No such file or directory: 'topo.json'
```

**Comment by teojgo** [comment]
@casparvl I was assuming that you are cloning the repo. You could try that because it is easier to edit the file.

**Comment by casparvl** [comment]
So... I ran into https://github.com/pypa/pip/issues/3532, which prompted me to remove the `.cache/pip/` cache dir. That magically seems to have resolved all my issues. 

```
$ reframe -C test-suite/config/${RFM_CONFIG_NAME} -c ${TEMPDIR}/test-suite/eessi/testsuite/tests/apps -R -t CI -t "1_node" -l
Detecting topology of remote partition 'citc:aarch64-graviton2-8c-16gb': this may take some time...
[ReFrame Setup]
  version:           4.2.1
  command:           '/tmp/rfm.HUUcEOZMZp/reframe_421/bin/reframe -C test-suite/config/aws_citc_autodetect.py -c /tmp/rfm.HUUcEOZMZp/test-suite/eessi/testsuite/tests/apps -R -t CI -t 1_node -l'
  launched by:       casparvl@mgmt.fair-mastodon.citc.local
  working directory: '/mnt/shared/home/casparvl'
  settings files:    '<builtin>', 'test-suite/config/aws_citc_autodetect.py'
  check search path: (R) '/tmp/rfm.HUUcEOZMZp/test-suite/eessi/testsuite/tests/apps'
  stage directory:   '/mnt/shared/home/casparvl/reframe_runs/stage'
  output directory:  '/mnt/shared/home/casparvl/reframe_runs/output'
  log files:         '/mnt/shared/home/casparvl/reframe_20230720_151246.log'

[List of matched checks]
- GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2020.4-foss-2020a-Python-3.8.2 /a108fe65
- GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=1_node %module_name=GROMACS/2020.1-foss-2020a-Python-3.8.2 /695f354c
Found 2 check(s)
```

Also tried with `4.3.2` btw, that also works now.

I can't really explain the earlier problems I had with 4.3.2, as those cannot be resolved by _just_ removing pip's cachedir. But I suppose maybe something in my environment broke the bootstrap for 4.3.2.

Anyway, consider this issue resolved, the problem was _very_ likely on my end. If other users encounter this, I'd suggest they remove their cachedir (`.cache/pip`) first and try again.
