### ISSUE TITLE
`scancel` running Slurm jobs if `reframe` is interrupted

### ISSUE THREAD

**Issue by jack-morrison** [reframe-hpc/reframe#3009]
When using the Slurm scheduler backend, it seems that interrupting `reframe` will stop new slurm jobs from being submitted, but any slurm job already running will continue to run.

This enhancement request is to take interruption one step further, and ensure that any running slurm job spawned by the `reframe` session is cleaned up via `scancel`.

**Comment by vkarak** [comment]
That sounds like a bug, because it should be cancelling the jobs in case the reframe process is interrupted with Ctrl-C. Could you give some more details on how to reproduce it?

**Comment by jack-morrison** [comment]
Yep - I'll get a reproducer together tomorrow!

**Comment by jack-morrison** [comment]
My apologies for the delay following up on this; I believe this is actually not a bug, and rather just a result of how I've setup `reframe` to run in our internal systems. Something for me to fix, not ReFrame to fix 😄

**Comment by jack-morrison** [comment]
confirmed this was my bad 🙃 , not RFM 👍
