### ISSUE TITLE
--distribute  capture hostname in wrong way 

### ISSUE THREAD

**Issue by ranaselim8** [reframe-hpc/reframe#3021]
![image](https://github.com/reframe-hpc/reframe/assets/87306045/69ebccf8-f7e1-41c9-92c1-65ed2e264e31)

**Comment by vkarak** [comment]
This is indeed a bug of the [function](https://reframe-hpc.readthedocs.io/en/stable/utility_functions_reference.html#reframe.utility.nodelist_abbrev) that is used to create the nodelist abbreviation with the `--distribute` option. It ignores the suffixes in the node name.

**Comment by vkarak** [comment]
@ranaselim8 Have you checked if the jobs are nonetheless submitted correctly, because it seems that this is just a formatting issue:

https://github.com/reframe-hpc/reframe/blob/c419112eb5261af1471e32fc58c8dfe3f5382ce6/reframe/frontend/testgenerators.py#L110
