### ISSUE TITLE
Parametrization of a Variable does not work with dependencies but works with Fixtures

### ISSUE THREAD

**Issue by rfeki** [reframe-hpc/reframe#3031]
I tried to run a Test that has some dependencies defined through `depends_on()`  using -P, --parameterize. It seems that parametrization of variables cannot resolve dependencies:
Error Example:
```
WARNING: could not resolve dependency: ('OSU_Mbw_Mr_1', 'XXXX, 'builtin') -> 'OSUBuild'
WARNING: could not resolve dependency: ('OSU_Mbw_Mr_0', 'XXXX', 'builtin') -> 'OSUBuild'
WARNING: skipping all dependent test cases
  - ('OSU_Mbw_Mr_0', 'XXXX', 'builtin')
  - ('OSU_Mbw_Mr_1', 'XXXX', 'builtin')
```

However, If I change the dependencies to Fixtures, it works. 
In my case, I have to use  dependencies to select specific variants at runtime and I need to parametrize a specific variable at the same time. **Any Ideas? or is it the same as --repeat**=N[¶](https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-repeat)  : Repeating tests with dependencies is not supported, but you can repeat tests that use fixtures.

**Comment by vkarak** [comment]
Exactly, it's as with the `--repeat` option and raw dependencies are not supported. I just realised this is not documented, so we should mention this explicitly in the docs.
