### ISSUE TITLE
4.5.0: unable to bootstap

### ISSUE THREAD

**Issue by j-ogas** [reframe-hpc/reframe#3085]
I am unable to bootstrap with (1) my Cray system python 3.6.15,  or (2) the supplemental python 3.10.9 provided via module.

3.6.15
```
$ python3 -V
Python 3.6.15
$ ./bootstrap.sh
==> python3 -m venv --without-pip /tmp/tmp.bnm6WmPenP
==> source /tmp/tmp.bnm6WmPenP/bin/activate
==> curl -s https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3
==> python3 -m pip install --no-cache-dir -q -r requirements.txt --target=external/x86_64/ --upgrade
/tmp/tmp.bnm6WmPenP/bin/python3: No module named pip
```

3.10
```
$ module load python
$ python3 -V
Python 3.10.9
$ ./bootstrap.sh
==> python3 -m venv --without-pip /tmp/tmp.12jqDrcBQR
==> source /tmp/tmp.12jqDrcBQR/bin/activate
==> curl -s https://bootstrap.pypa.io/get-pip.py | python3
==> python3 -m pip install --no-cache-dir -q -r requirements.txt --target=external/x86_64/ --upgrade
/tmp/tmp.12jqDrcBQR/bin/python3: No module named pip
```

**Comment by teojgo** [comment]
Under the `curl` command that gets pip for you, you should see something like this:
```
curl -s https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3
Collecting pip<22.0
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Collecting setuptools
  Using cached setuptools-59.6.0-py3-none-any.whl (952 kB)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools, pip
Successfully installed pip-21.3.1 setuptools-59.6.0 wheel-0.37.1
```

**Comment by vkarak** [comment]
The bootstrap script works differently in 4.5. It starts a pip-less virtual environment and downloads pip and installs it. Can you run successfully the `curl` command from the machine that you try to install reframe in?

```bash
curl -s https://bootstrap.pypa.io/pip/3.6/get-pip.py
```

**Comment by j-ogas** [comment]
> The bootstrap script works differently in 4.5. It starts a pip-less virtual environment and downloads pip and installs it. Can you run successfully the `curl` command from the machine that you try to install reframe in?
> 
> ```shell
> curl -s https://bootstrap.pypa.io/pip/3.6/get-pip.py
> ```

Unfortunately it does not, we are behind a whitelist firewall. I suppose I could try and pester our site admins to allow the URL above.

**Comment by vkarak** [comment]
We could ship the `get-pip` script with reframe and resort to this in the bootstrap script if the download fails.

**Comment by j-ogas** [comment]
> We could ship the `get-pip` script with reframe and resort to this in the bootstrap script if the download fails.

That would be lovely.
