### ISSUE TITLE
Versioning link on Read the Docs documentation does not work for version >= 4.5.0

### ISSUE THREAD

**Issue by teojgo** [reframe-hpc/reframe#3112]
I seems that the updating of the sphinx theme is to blame: https://github.com/reframe-hpc/reframe/commit/85403ea752df4a0db1bbaee63c1e725d1b0ca116

**Comment by teojgo** [comment]
Yes, the fix was merged to master, not to develop.

**Comment by vkarak** [comment]
Yes, but should't stable which corresponds to `master` work?
