### ISSUE TITLE
reframe-hpc.readthedocs search doesn't return

### ISSUE THREAD

**Issue by jack-morrison** [reframe-hpc/reframe#3126]
It seems to me that the search function of the docs may be broken. I observe the following "Searching..." but no results returned.

<img width="1340" alt="image" src="https://github.com/reframe-hpc/reframe/assets/32687739/b94b12ea-c887-4e62-82c2-467c62c532bc">

**Comment by vkarak** [comment]
Yes, I've noticed that too and it was due to an update in doc dependencies. That's fixed in #3121 and should be released in 4.5.2. Could you try the provisional https://reframe-hpc.readthedocs.io/en/master?

**Comment by jack-morrison** [comment]
@vkarak Ah, great - yes it looks like it's fixed on master.
