### ISSUE TITLE
possible bug in reframe logging

### ISSUE THREAD

**Issue by xinye83** [reframe-hpc/reframe#3127]
[reframe-bug.tar.gz](https://github.com/reframe-hpc/reframe/files/14424311/reframe-bug.tar.gz)

Steps to reproduce after downloading the attached tarball
```
tar -xf reframe-bug.tar.gz
cd reframe-bug
module load cray-python
python3 -m venv venv
pip install reframe-hpc
reframe -C config.py -c test.py -r
```

The tests defined in `run_2` are OK but those defined in `run_1` all give a logging error.

**Comment by vkarak** [comment]
What is the exact log error that you get? One obvious thing I see is that you don't activate the venv environment before install reframe, so you're doing a global installation.

**Comment by xinye-hpe** [comment]
I can't reproduce this issue with reframe 4.6.1 (with or without activating the virtual env). Looks like the original conversation on Slack was more than 90 days ago and is hidden.

**Comment by vkarak** [comment]
Closing this then. Feel free to reopen if you hit it again.
