### ISSUE TITLE
Setting variable(bool, value=True) from the command line not behaving as expected

### ISSUE THREAD

**Issue by homerdin** [reframe-hpc/reframe#3144]
Hello.  I'm trying to implement a test which has a `concurrent = variable(bool, value=True)`.  We are interested in overwriting this value from the command line, but I'm unable to get a value of `False` to be set by passing `-S concurrent=no`, `-S concurrent=false`, or `-S concurrent=0`.

I'm able to work around this by using a `variable(str, value='True')` and changing the comparisons.  

This is with version `4.5.1`

**Comment by vkarak** [comment]
That's expected, check the [note](https://reframe-hpc.readthedocs.io/en/stable/manpage.html#cmdoption-S) for the `-S` option:

> Boolean variables in a test must be declared of type [Bool](https://reframe-hpc.readthedocs.io/en/stable/utility_functions_reference.html#reframe.utility.typecheck.Bool) and not of the built-in [bool](https://docs.python.org/3/library/functions.html#bool) type, in order to adhere to the aforementioned behaviour. If a variable is defined as [bool](https://docs.python.org/3/library/functions.html#bool) there is no way you can set it to [False](https://docs.python.org/3/library/constants.html#False), since all strings in Python evaluate to [True](https://docs.python.org/3/library/constants.html#True).

So you will have to define the variable as

```python
import reframe.utility.typecheck as typ


class Test(...):
    concurrent = variable(typ.Bool, value=True)
```

**Comment by homerdin** [comment]
Thanks! I'll update my tests.
