### ISSUE TITLE
Problematic formatting of perflog headers when using `perflog_compat`

### ISSUE THREAD

**Issue by teojgo** [reframe-hpc/reframe#3163]
For example for the perflog header based on format: https://github.com/eth-cscs/cscs-reframe-tests/blob/dea38f67cd1c5ff9d80f7dbd785854733433d86d/config/common.py#L54

A final header looks as follows:
`job_completion_time|version|info|jobid|num_tasks|perf_var=perf_value|perf_ref perf_lower_thres,perf_upper_thres)perf_unit`

**Comment by vkarak** [comment]
Oh yeah, I've come across it and have noted it down to open an issue about.

**Comment by vkarak** [comment]
This happens when you use the `perflog_compat` only.

**Comment by vkarak** [comment]
I think the header generator gets confused from the spaces and the parenthesis in the format. Here is the regex used:

https://github.com/reframe-hpc/reframe/blob/09ae0293001696656ec548dc0fcc1378a20bc7cf/reframe/core/logging.py#L172

And here the groups extracted:

https://github.com/reframe-hpc/reframe/blob/09ae0293001696656ec548dc0fcc1378a20bc7cf/reframe/core/logging.py#L191-L193
