### ISSUE TITLE
`check_#ALL` format spec for perf handler does not work  

### ISSUE THREAD

**Issue by mszpindler** [reframe-hpc/reframe#3176]
Specifying `%(check_#ALL)s|` alone as `format` for  `handlers_perflog` fails to work.

**Comment by mszpindler** [comment]
```
'handlers_perflog': [
                {
                    'type': 'filelog',
                    'prefix': '%(check_system)s/%(check_partition)s',
                    'level': 'verbose',
                    'format': '%(check_#ALL)s',
                    'datefmt': '%FT%T%:z',
                    'append': True,
                },
            ]
```
In the config file reproduces the issue.

**Comment by ekouts** [comment]
Some more comments:
- If another record attribute is defined in the format, before or after `%(check_#ALL)s`, it works fine.  For example: `'format': '%(check_result)s|%(check_#ALL)s',`
- The error is coming from this line: https://github.com/reframe-hpc/reframe/blob/e461596543a4df38a8bdfabd78395d307d41eb29/reframe/core/logging.py#L304

It is easily fixable if we disable the validation (checks if `fmt` and `style` are mismatched): 
```python
    def __init__(self, fmt=None, datefmt=None, perffmt=None,
                 ignore_keys=None, style='%'):
        super().__init__(fmt, datefmt, style, validate=False)
```
but maybe there is a better solution.
