### ISSUE TITLE
In favor of proper python packaging?

### ISSUE THREAD

**Issue by createyourpersonalaccount** [reframe-hpc/reframe#3194]
Hello,

After looking at your installation process, I've realized that you're using a bootstrap.sh script. Why aren't you bundling reframe with a pyproject.toml using setuptools?

For example, your bootstrap script is installing pip 3.6 no matter what, (but why? my pip worked just fine with requirements.txt.) The entry point is bin/reframe instead of a cli entry point in pyproject.toml

I'm willing to convert this project to a proper python package, but I'm asking ahead of time to know
1) if you are interested
2) if there's some technicalities to keep in mind that make the bootstrap script important

**Comment by vkarak** [comment]
There is a proper Python package if you like to use it: `pip install reframe-hpc`. We simply haven't switched from `setup.cfg` to `pyproject.toml`.

The bootstrap script offers a different method of installation and its purpose is to allow a sandboxed installation outside a virtual environment. It installs all dependencies in a directory in the installation prefix and the `bin/reframe` entry point makes sure to use this. It also allows us to run it on systems where pip is not available. Many users are using this method, so we are not planning to get rid of it.

**Comment by createyourpersonalaccount** [comment]
Hello @vkarak 

Thanks for the clarification. I think it's fine then.
