### ISSUE TITLE
Add cli option to ignore `valid_systems` and `valid_prog_environs`

### ISSUE THREAD

**Issue by teojgo** [reframe-hpc/reframe#3217]
As a user I would like to ignore the `valid_systems` and the `valid_prog_environs` and try a test no matter what the requirements might be. 

This can be done now by setting the variables `-S 'valid_systems=*' -S 'valid_prog_environs=*'` but it would be nice to have an option for this.

**Comment by vkarak** [comment]
We do have the `--skip-system-check` and `--skip-prgenv-check` that do exactly that.

**Comment by teojgo** [comment]
Yes, indeed I overlooked those options. They do the job.
