### ISSUE TITLE
Specify run-report path from within a test

### ISSUE THREAD

**Issue by tanguypierre** [reframe-hpc/reframe#3240]
Hi,

I would like to specify the run-report path from within a test. _Is this even possible?_

I've tried to access and modify the loaded configuration with commands like `reframe.core.settings.site_configuration['general']`, `rt.runtime().site_config['general']`, or exporting the `RFM_REPORT_FILE` environment variable from within the test.
These attempts were quite logically unsuccessful.

As I am currently writing tests for a scientific application and want to create a database for my results, it would be helpful for storing the results at the right place without any postprocessing.
I pass some paths to Reframe as variables for launching my application. It would be nice if I could name the run-report after these paths. 
Using the `--report-file` command-line option won’t fit my case as the desired name will be built depending on some results.

_Maybe adding a `run-report-prefix` in the site_configuration, which could be extended, might also be an idea._

Thanks for your work

**Comment by vkarak** [comment]
Hi @tanguypierre we are working on introducing permanent DB storage for run results with functionality for comparing performance results and querying past reports in #3227.

**Comment by tanguypierre** [comment]
Thanks for your update!
The work being done in the mentioned PR looks great and will be helpful for many. Eagerly looking forward to its deployment.

**Comment by vkarak** [comment]
Closing issue as PR #3227 is merged and will be released in 4.7.
