### ISSUE TITLE
Add support for a plugin log handler

### ISSUE THREAD

**Issue by dmargala** [reframe-hpc/reframe#3270]
I'd like to be able to define a custom log handler in a configuration file. This sort of capability seems similar to the idea of enabling custom launchers described in the [extending-the-framework](https://reframe-hpc.readthedocs.io/en/stable/howto.html#extending-the-framework) section of the docs.

I poked around the code base a bit and hacked together some minimal changes here: https://github.com/dmargala/reframe/tree/add-plugin-log-handler

With the changes on that branch, I can define add my custom log handler by including something like this in my config file:

```python
class PlugInLogHandler(logging.Handler):
    def emit(self, record):
        custom_logger.log(record)

def _create_plugin_handler(site_config, handlers_group):
    return PlugInLogHandler()

from reframe.core.logging import register_create_handler
register_create_handler('plugin', _create_plugin_handler)
```

Does this seem like a reasonable capability to add? Is there maybe a better way to go about implementing this capability?

**Comment by vkarak** [comment]
Hi @dmargala, I think that makes sense to add. I remember NERSC had to maintain a custom logging handler and thus a custom ReFrame fork for something that is orthogonal to the rest of the framework. I encourage you to open a PR with this functionality.

**Comment by dmargala** [comment]
Thank you @vkarak for your help out with this! 

>  I remember NERSC had to maintain a custom logging handler and thus a custom ReFrame fork for something that is orthogonal to the rest of the framework.

Yes that is precisely the case. Maintaining our fork + customizations has been slowing us down from picking up new features. I think we'll be able to use 4.7 directly now 🎉
