### ISSUE TITLE
Problem with scheduler

### ISSUE THREAD

**Issue by laraPPr** [reframe-hpc/reframe#3279]
With the newer versions of ReFrame it cannot keep track of the submitted jobs with SLURM on our system at Ghent University.

With ReFrame version 4.5.1 everything runs with `'scheduler': 'slurm'`

If i use the same sheduler with ReFrame 4.6.2 than the jobs get submitted but ReFrame does not see when they are completed. So ReFrame is endlessly waiting for the jobs to finish

if i use `squeue` as the scheduler with ReFrame 4.6.2 than the jobs get submitted but reframe already does the sanity check of the output before the jobs are finished and so all the tests fail while the submitted jobs keep running on the system.

**Comment by teojgo** [comment]
@laraPPr could you try adding `check=True` to https://github.com/reframe-hpc/reframe/blob/fe588bde51bfa4a360dd2981108ae79b567a9065/reframe/core/schedulers/slurm.py#L495 to see if the problem comes from this?

**Comment by laraPPr** [comment]
> @laraPPr could you try adding `check=True` to
> 
> https://github.com/reframe-hpc/reframe/blob/fe588bde51bfa4a360dd2981108ae79b567a9065/reframe/core/schedulers/slurm.py#L495
> 
> to see if the problem comes from this?

like this? `completed = osext.run_command('squeue -h -j %s -o %%r' % job.jobid, check=True)`

Tried it with both `squeue` and `slurm` and saw the problem that I had before.

**Comment by teojgo** [comment]
> > @laraPPr could you try adding `check=True` to
> > https://github.com/reframe-hpc/reframe/blob/fe588bde51bfa4a360dd2981108ae79b567a9065/reframe/core/schedulers/slurm.py#L495
> > 
> > to see if the problem comes from this?
> 
> like this? `completed = osext.run_command('squeue -h -j %s -o %%r' % job.jobid, check=True)`
> 
> Tried it with both `squeue` and `slurm` and saw the problem that I had before.

Yes, like you did. Then the issue is coming from a different place...

**Comment by teojgo** [comment]
@laraPPr can you try also with 4.6.0 and see it it happens?

**Comment by laraPPr** [comment]
No it does not than it works with `slurm` and `squeue` as scheduler

**Comment by teojgo** [comment]
> No it does not than it works with `slurm` and `squeue` as scheduler

I cannot understand if it works fine in 4.6.0 from the above.

**Comment by vkarak** [comment]
So it works for 4.6.0 and not for 4.6.2? We could bisect the changes and find the offending commit.

**Comment by laraPPr** [comment]
Also does not work in 4.6.1. 
Is their a way to get the output of the `sacct` command in the run stage?

From what I understand it seems to change the environment when `entering stage: run`. And from that environment it is no longer able to  successfully run 'sacct' and `scancel` on our system. But the first time it does the `entering stage: run` it does work for the `sbatch` commando.

And excerpt from the log  
```
Entering stage: compile
Entering stage: compile
Entering stage: compile_wait
Entering stage: run
Copying PATH_TO/EESSI/test-suite/eessi/testsuite/tests/apps/lammps/src/rhodo to stage directory
Symlinking files: ['data.rhodo']
Generating the run script
[CMD] 'sbatch --export=None --clusters=skitty rfm_job.sh'
Spawned run job (id=7661032)
Entering stage: run
Copying PATH_TO/EESSI/test-suite/eessi/testsuite/tests/apps/lammps/src/lj to stage directory
Symlinking files: []
Generating the run script
[CMD] 'sbatch --export=None --clusters=skitty rfm_job.sh'
Spawned run job (id=7661033)
[CMD] 'sacct -S 2024-10-09 -P -j 7661032,7661033 -o jobid,state,exitcode,end,nodelist'
Entering stage: run
Entering stage: run
[CMD] 'sacct -S 2024-10-09 -P -j 7661032,7661033 -o jobid,state,exitcode,end,nodelist'
Entering stage: run
Entering stage: run
[CMD] 'scancel 7661032'
```

**Comment by laraPPr** [comment]
And yes it works for 4.6.0

**Comment by vkarak** [comment]
This is very strange, the only change in the Slurm backends between these two versions is #3184 and it should affect the `squeue` backend not the `slurm` that you are using.

**Comment by laraPPr** [comment]
I have reversed the changes in #3184 to see if that would resolve it. It did not I think it is not caused by changes in the Slurm backend but it is caused by some changes more highlevel than the Slurm Backend.

**Comment by vkarak** [comment]
Instead of manually reverting the changes and retrying, would you mind doing a `git bisect` between versions 4.6.0 and 4.6.1 so that we find the exact offending commit?

**Comment by laraPPr** [comment]
It is this PR #3206. With this commit the error started to occurring 1e47b20c5850aaa6f40f9cfae9afa1da3bf57794.

**Comment by laraPPr** [comment]
Its this line https://github.com/reframe-hpc/reframe/blob/fe588bde51bfa4a360dd2981108ae79b567a9065/reframe/frontend/cli.py#L583        
`'--purge-env', action='store_true', dest='purge_env',`
When I change it back, it works as before
`'--purge-env', action='store_true', dest='purge_env', default=False,`

**Comment by laraPPr** [comment]
I was causing it myself and the change in the PR started triggering it. 
I had set the following in my config
`'purge_environment': True,`
I changed it to `False` and it is now working as expected

**Comment by laraPPr** [comment]
Thank you for all the help

**Comment by vkarak** [comment]
Yes, actually #3206 was indeed fixing a bug. The current behaviour is the correct one.
