### ISSUE TITLE
Add option to silence warning for skip/skip_if

### ISSUE THREAD

**Issue by tom91136** [reframe-hpc/reframe#3284]
Hello, Bristol site here 😀

We have a fairly large parameter space that tries to compile and run a benchmark (i.e BabelStream, with programming model and compiler as parameters).
Right now we have about 10% of the cases being skipped, is there a less severe logging level that conveys the skipped tests are by design and intended?
In our case the parameter packs are not flexible enough because the tests are generated from a custom spec YAML file similar to the ones in the tutorial.

**Comment by vkarak** [comment]
Currently, you can't change this, but I agree that it shouldn't be a warning. Maybe we can push it to the `verbose` level so that you only see it when running with `-v`.
